ingame-app/ingame

server/src/apis/profilephoto.entity.ts
server/src/apis/quest.entity.ts
server/src/apis/sidequest.entity.ts
server/src/apis/user.entity.ts
server/src/apis/userinfo.entity.ts

<strong>
Closes #13 
</strong>
- 데이터베이스 테이블에 해당하는 엔티티 생성
- [TypeORM 공식 홈페이지](https://typeorm.io/)
- [DB 스키마](https://prgrms.notion.site/DB-c3a48c3e94944180b1097f78546eab61)

[BE] 엔티티 생성 완료

---

client/package-lock.json
client/package.json
client/src/App.tsx
client/src/index.tsx
client/src/pages/counter.tsx
client/src/store/counterSlice.ts
client/src/store/index.ts

close #19 
기존 세팅 시, redux-toolkit은 이미 설치하였기 때문에 react-redux만 추가로 설치하였습니다.
```bash
npm install react-redux
```
해당 폴더 아래에 redux 관련 코드들을 생성하였습니다.
```ts
//counterSlice.ts
import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';
export interface CounterState {
value: number;
}
const initialState: CounterState = {
value: 0,
};
export const counterSlice = createSlice({
name: 'counter',
initialState,
reducers: {
increment: (state) => {
// Redux Toolkit allows us to write "mutating" logic in reducers. It
// doesn't actually mutate the state because it uses the Immer library,
// which detects changes to a "draft state" and produces a brand new
// immutable state based off those changes
state.value += 1;
},
decrement: (state) => {
state.value -= 1;
}, …
```

[FE] 프론트엔드 Redux 초기 설정

---

client/src/App.tsx
client/src/constant/route.ts
client/src/pages/Error.tsx
client/src/pages/Login.tsx
client/src/pages/MainPage.tsx
client/src/pages/Ranking.tsx
client/src/pages/SignUp.tsx
client/src/routes/routing.tsx

closes #23 
MainPage 외 4개 생성하였습니다. Templete은 FE 공통 snippet 사용했습니다.
```tsx
// MainPage.tsx
import styled from 'styled-components';
import React from 'react';
const MainPage = () => {
return (
<MainPageStyle>
<h1>MainPage</h1>
</MainPageStyle>
);
};
const MainPageStyle = styled.div``;
export default MainPage;
```
path 주소를 constant/route.ts 에 작성했고 이후 route에 사용될 상수들은 여기에 적어주시면 됩니다.
```ts
export const ROUTERS = {
MAIN: '/',
AUTH: {
LOGIN: '/login',
SIGNUP: '/signup',
},
RANK: '/ranking',
} as const;
```
잘못된 URL로 접속 했을 시 Error.tsx 페이지로 이동하는 코드를 추가했습니다.
```tsx
// routing.tsx
import { ROUTERS } from '@/constant/route';
import Layout from '@/layout/Layout';
import Login from '@/pages/Login';
import MainPage from '@/pages/MainPage';
import Error from '@/pages/Error';
import { createBrowserRouter } …
```

[FE] 프론트엔드 Route설정 및 각 페이지 생성

---

client/package-lock.json
client/package.json
client/src/components/Button.tsx
client/src/components/Dropdown.tsx
client/src/components/InputBox.tsx
client/src/components/Top.tsx
client/src/constant/route.ts
client/src/hooks/useOutsideClick.ts
client/src/layout/Layout.tsx
client/src/pages/MainPage.tsx
client/src/pages/Test.tsx
client/src/routes/routing.tsx
client/src/styles/styled.d.ts
client/src/styles/theme.ts

<strong>
Closes #25
</strong>
```bash
npm install react-icons --save
```
```ts
// theme.ts
const color = {
...
grayDark: '#b0b0b0',
grayDarkActive: '#8d8d8d',
};
// styled.d.ts
color: {
...
grayDark: string;
grayDarkActive: string;
};
```
input 박스 후위에 text 또는 icon이 올 수 있도록 분기 처리를 위해 추가하였습니다. text는 현재 프로젝트에서 "인증하기"만 사용하므로 하드코딩 되어있습니다. 추후 확장성을 위해 따로 text를 props로 받도록 변경 될 수 있습니다.
```tsx
import React, { ForwardedRef, useState } from 'react';
import styled from 'styled-components';
import { MdOutlineEmail } from 'react-icons/md';
import { BsKey } from 'react-icons/bs';
import { FaRegSmile } from 'react-icons/fa';
import { IoEye, IoEyeOff } from 'react-icons/io5';
type endType = 'text' | 'icon';
interface Props extends React.InputHTMLAttributes<HTMLInputElement> {
placeholer?: string; …
```

[FE] 공통 컴포넌트 개발 (1)

---

client/src/layout/Layout.tsx
client/src/models/profilePhoto.model.ts
client/src/models/quest.model.ts
client/src/models/sideQuest.model.ts
client/src/models/user.model.ts
client/src/models/userInfo.model.ts

Closes #31 
```tsx
// user.model.ts
export interface User {
id: number;
email: string;
password?: string;
createdAt: string;
updatedAt: string;
}
```
```tsx
height: 800px;
${media.mobile} {
height: 100%;
min-height: 800px;
}
```

[FE] Model 파일 생성, Interface 설정

---

server/package-lock.json
server/package.json
server/src/apis/users/dto/create-user.dto.ts
server/src/apis/users/dto/update-user.dto.ts
server/src/apis/users/dto/user-response.dto.ts
server/src/apis/users/entities/profile-photo.entity.ts
server/src/apis/users/entities/user-info.entity.ts
server/src/apis/users/entities/user.entity.ts
server/src/apis/users/users.controller.ts
server/src/apis/users/users.module.ts
server/src/apis/users/users.service.ts
server/src/config/typeorm.config.ts

<strong>
Closes #16 
</strong>
[엔티티 관련 commit](https://github.com/ingame-app/ingame/commit/e99f3ed)
- 회원탈퇴 시 관계 형성된 데이터 삭제되도록 설정
```ts
@OneToOne(() => User, (user) => user.profilePhoto, { onDelete: 'CASCADE' })
@JoinColumn({ name: 'user_id' })
user: User;
```
- user 조회 시 관계 맵핑된 테이블 데이터 함께 조회되도록 설정
```ts
@OneToOne(() => UserInfo, (userInfo) => userInfo.user, {
onDelete: 'CASCADE',
eager: true,
})
userInfo: UserInfo;
```
[회원가입 기능 관련 commit](https://github.com/ingame-app/ingame/commit/1436293)
- 이미 존재하는 회원인지 검증
```ts
const existingUser = await this.userRepository.findOne({ where: { email } });
if (existingUser) {
throw new HttpException('이미 존재하는 회원입니다', HttpStatus.CONFLICT);
}
```
- bcrypt 암호 적용
```ts
const saltRounds = parseInt(this.configService.get<string>('SALT_ROUNDS'));
const salt = …
```

[BE] 사용자 API 기능 1차 구현 완료

---

server/.gitignore
server/package-lock.json
server/package.json
server/src/apis/auth/auth.controller.ts
server/src/apis/auth/auth.guard.ts
server/src/apis/auth/auth.module.ts
server/src/apis/auth/auth.service.ts
server/src/apis/auth/dto/create-auth.dto.ts
server/src/apis/auth/dto/jwt-payload.dto.ts
server/src/apis/auth/dto/login-user.dto.ts
server/src/apis/auth/dto/update-auth.dto.ts
server/src/apis/users/dto/profile-photo.dto.ts
server/src/apis/users/dto/update-user.dto.ts
server/src/apis/users/entities/user.entity.ts
server/src/apis/users/users.controller.ts
server/src/apis/users/users.module.ts
server/src/apis/users/users.service.ts
server/src/commons/decorators/auth.decorator.ts
server/src/config/jwt.config.ts

<strong>
Closes #35 
</strong>
- 입력한 이메일에 해당하는 사용자가 없거나 비밀번호가 틀리다면, 에러 발생
- payload에 id와 email 입력
```ts
// auth.service.ts
async login(loginUserDto: LoginUserDto) {
const { email, password } = loginUserDto;
const user = await this.usersService.getUserByEmail(email);
const verifyPassword = await bcrypt.compare(password, user.password);
if (!user || !verifyPassword) {
throw new UnauthorizedException();
}
const payload: JwtPayloadDto = {
id: user.id,
email: user.email,
};
const accessToken = await this.jwtService.signAsync(payload);
return accessToken;
}
```
- AuthGuard를 이용하여 토큰 검증
- 토큰을 검증해서 payload 값을 뽑아낸 후, request의 user 키에 값을 넣어 전달
- 토큰이 존재하지 않거나 검증에 실패했다면 에러 발생
- true를 리턴하면 요청이 계속 진행되도록 한다
```ts
// auth.guard.ts
@Injectable()
export class AuthGuard implements CanActivate {
constructor( …
```

[BE]Auth API 기능 구현과 Users API 수정 및 기능 추가 완료

---

server/src/apis/ranking/dto/create-ranking.dto.ts
server/src/apis/ranking/dto/ranking-response.dto.ts
server/src/apis/ranking/dto/update-ranking.dto.ts
server/src/apis/ranking/ranking.controller.ts
server/src/apis/ranking/ranking.module.ts
server/src/apis/ranking/ranking.service.ts
server/src/apis/users/users.service.ts

<strong>
Closes #44 #45  
</strong>
- 랭킹 조회 기능 구현
- 회원가입 기능 수정
- 포인트가 같을 시 순위 동일하도록 설정
- 유저 정보에서 순위 정보 추가하여 보내주기
```ts
// ranking.service.ts
import { Injectable } from '@nestjs/common';
import { UsersService } from '../users/users.service';
import { RankingResponseDto } from './dto/ranking-response.dto';
@Injectable()
export class RankingService {
constructor(private readonly usersService: UsersService) {}
async getRanking(): Promise<RankingResponseDto[]> {
const users = await this.usersService.getAllUser();
let currentRank = 1;
let lastUserPoint = 0;
let countCurrentRank = 0;
const ranking = users.map((user) => {
if (user.point !== lastUserPoint) {
currentRank += countCurrentRank;
countCurrentRank = 1;
} else {
countCurrentRank++;
}
const rankedUser = new RankingResponseDto(user, …
```

[BE] 랭킹 조회 및 회원가입 수정 완료

---

client/src/api/auth.api.ts
client/src/components/Dropdown.tsx
client/src/components/Hamberger.tsx
client/src/components/RankingCard.tsx
client/src/components/RankingCardList.tsx
client/src/constant/api.ts
client/src/hooks/useAuth.ts
client/src/mocks/browser.ts
client/src/mocks/handlers/auth.ts
client/src/pages/Login.tsx
client/src/pages/Main.tsx
client/src/pages/Ranking.tsx
client/src/pages/Test.tsx
client/src/store/authSlice.ts
client/src/utils/axios.ts
client/src/utils/tokenUtils.ts

<strong>
Closes #47 
</strong>
공통 Dropdown의 기능이 바뀌지 않기때문에 Hamburger 아이콘을 Dropdown의 기본 아이콘으로 넣고 세부 기능 또한 Dropdown 한 곳에서 추가 수정할 수 있게 합쳤습니다.
```tsx
const Dropdown = ({ isOpen = false }: DropdownProps) => {
const [open, setOpen] = useState(isOpen);
const dropdownRef = useOutsideClick<HTMLDivElement>(open, () => setOpen(false));
const { userLogout } = useAuth();
return (
<DropdownStyle $open={open} ref={dropdownRef}>
<button className="toggle" onClick={() => setOpen(!open)}>
<GiHamburgerMenu />
</button>
{open && (
<div className="panel">
<ul>
<li>
<Link className="link-styles" to={ROUTERS.MAIN}>
메인 화면
</Link>
</li>
<li>
<Link className="link-styles" to={ROUTERS.RANK}>
랭킹
</Link>
</li>
<li>
<button onClick={userLogout}>로그아웃</button>
</li>
<li>
<button>회원 탈퇴</button>
</li>
</ul>
</div>
)} …
```

[FE] 드롭다운 기능 추가 개발 및 랭킹 페이지 너비 수정

---

client/src/api/auth.api.ts
client/src/api/users.api.ts
client/src/components/CloseButton.tsx
client/src/components/EditProfileButton.tsx
client/src/components/QuestInputBox.tsx
client/src/components/UserProfile.tsx
client/src/components/modals/ProfileModal.tsx
client/src/constant/api.ts
client/src/constant/queryKey.ts
client/src/mocks/browser.ts
client/src/mocks/data/mockUser.ts
client/src/mocks/handlers/users.ts

Closes #40 
```tsx
// ProfileModal.tsx
import styled from 'styled-components';
import { useForm } from 'react-hook-form';
import QuestInputBox from '../QuestInputBox';
import ProfileIntroInputBox from '../ProfileIntroInputBox';
import { FaUser } from 'react-icons/fa';
import { FaUserPen } from 'react-icons/fa6';
import Button from '../Button';
import CloseButton from '../CloseButton';
import { useMutation } from '@tanstack/react-query';
import { patchUserProfile } from '@/api/users.api';
import { useState } from 'react';
interface ProfileModifyProps {
nickname: string,
intro: string
}
interface ProfileProps {
onClose: () => void;
OriginNickname: string;
OriginIntro: string;
}
const ProfileModal = ({ onClose, OriginNickname, OriginIntro }: ProfileProps) => {
const [nickname, setNickname] = …
```

[FE] 프로필 모달 기능 구현

---

server/src/apis/quests/dto/create-quest.dto.ts
server/src/apis/quests/dto/create-side-quest.dto.ts
server/src/apis/quests/dto/update-side-quest.dto.ts
server/src/apis/quests/entities/quest.entity.ts
server/src/apis/quests/entities/side-quest.entity.ts
server/src/apis/quests/enums/quest.enum.ts
server/src/apis/quests/quests.controller.ts
server/src/apis/quests/quests.service.ts

<strong>
Closes #26 
</strong>
- 메인 퀘스트 생성 기능 구현
- 메인 퀘스트 전체 조회 기능 구현
- 메인 퀘스트 수정 기능 구현
- 메인 퀘스트 삭제 기능 구현
<br><br>
**공통사항**
UseGuards + AuthGuard로 토큰 검증 (thanks to 원익님)
**메인 퀘스트 생성 기능**
- 메인 퀘스트와 사이드 퀘스트 분리하여 쿼리
```ts
async create(id: number, createQuestDto: CreateQuestDto) {
const currentDate = new Date();
const { title, difficulty, mode, side, startDate, endDate, hidden, status } = createQuestDto;
const queryRunner = this.dataSource.createQueryRunner();
await queryRunner.connect();
await queryRunner.startTransaction();
try {
const quest = this.questRepository.create({
userId: id,
title: title,
difficulty: difficulty,
mode: mode,
startDate: startDate,
endDate: endDate,
hidden: hidden,
status: status,
createdAt: currentDate,
updatedAt: currentDate,
});
const savedQuest = await …
```

[BE] 메인 퀘스트 API 기능 구현

---

server/src/apis/quests/quests.controller.ts

-  서브 퀘스트 생성 기능 구현 (메인 퀘스트 생성 기능과 통합)
- 서브 퀘스트 전체 조회 기능 구현
- 서브 퀘스트 수정 기능 구현
- 서브 퀘스트 삭제 기능 구현
<br><br>
- (추후 추가 예정)
<br><br>
- (없음)
<br><br>
- (없음 -> 팀 노션 API 문서 참조)
<br><br>

[BE] 서브 퀘스트 API 기능 구현

---

server/src/apis/quests/quests.module.ts
server/src/apis/quests/quests.service.ts

-  TypeORM 모듈 호출 누락으로 인한 실행 불가 에러 수정
<br><br>
- (추후 추가 예정)
<br><br>
- (없음)
<br><br>
- (없음)
<br><br>

[BE] [긴급] 서브 퀘스트 API 기능 구현

---

server/src/apis/quests/dto/create-quest.dto.ts
server/src/apis/quests/dto/create-side-quest.dto.ts
server/src/apis/quests/dto/update-side-quest.dto.ts
server/src/apis/quests/quests.controller.ts
server/src/apis/quests/quests.service.ts

<strong>
Closes #59 
</strong>
- 사이드 퀘스트 생성 기능 구현
- 사이드 퀘스트 수정 기능 구현
- 사이드 퀘스트 삭제 기능 구현
<br><br>
**공통사항**
UseGuards + AuthGuard로 토큰 검증
**사이드 퀘스트 생성 기능**
- 메인 퀘스트 생성 함수에서 분리
``` ts
async createSide(id: number, createQuestDto: CreateSideQuestDto) {
const currentDate = new Date();
const { quests } = createQuestDto;
const queryRunner = this.dataSource.createQueryRunner();
await queryRunner.connect();
await queryRunner.startTransaction();
try {
for (const [idx, it] of quests.entries()) {
const { questId, content, status, createdAt, updatedAt } = it;
const quest = this.questRepository.find({ where: { id: questId, userId: id } });
if (!quest) {
throw new HttpException('fail - Quest not found', HttpStatus.NOT_FOUND);
}
const side = this.sideQuestRepository.create({
id: idx,
questId: questId, …
```

[BE] 사이드 퀘스트 API 구현

---

client/src/provider/loginProvider.tsx
client/src/routes/routing.tsx

<strong>
Closes #82 
</strong>
redux로 상태관리중인 로그인 여부 값을 가져와서 현재 상태를 판별 후 로그인이 되어있지 않으면 로그인 화면으로 가도록 구현하였습니다. 로그인 화면에서 회원가입 페이지로의 이동은 허용하도록 수정하였습니다.
```tsx
import { isLoggedIn } from '@/store/authSlice';
import { useEffect } from 'react';
import { useSelector } from 'react-redux';
import { useNavigate, useLocation } from 'react-router-dom';
interface LoginProviderProps {
children: React.ReactNode;
}
const LoginProvider = ({ children }: LoginProviderProps) => {
const navigate = useNavigate();
const isLogin = useSelector(isLoggedIn);
const location = useLocation();
useEffect(() => {
if (!isLogin && location.pathname !== '/signup') {
navigate('/login');
}
}, [isLogin, location.pathname, navigate]);
return <>{children}</>;
};
export default LoginProvider;
```
element를 LoginProvider로 감싸주었습니다. …

[FE] login Provider 구현

---

client/src/hooks/useCreateQuest.ts
client/src/hooks/useEditQuest.ts
client/src/pages/CreateMainQuest.tsx
client/src/pages/EditMainQuest.tsx

Closes #79
```ts
// uesCreateQuest.ts
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { useMutation } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Quest, QuestHiddenType } from '@/models/quest.model';
import { createMainQuest } from '@/api/quests.api';
interface SideContent {
content: string;
}
interface CreateMainQuestProps extends Quest {
title: string;
difficulty: number;
side: SideContent[];
startDate: string;
endDate: string;
hidden: QuestHiddenType;
}
export const useCreateQuest = () => {
const [isPrivate, setIsPrivate] = useState(false);
const [isDifficulty, setIsDifficulty] = useState(0);
const [startDate, setStartDate] = useState('');
const [endDate, setEndDate] = useState('');
const today = new …
```

[FE] CreateMainQuest,EditMainQuest페이지 기능 hooks로 분리

---

client/package.json
client/src/api/quests.api.ts
client/src/components/CreateSubQuestButton.tsx
client/src/components/SubBox.tsx
client/src/components/modals/CreateSubQuestModal.tsx
client/src/components/modals/SubQuestModal.tsx
client/src/constant/queryKey.ts
client/src/hooks/useQuest.ts
client/src/index.tsx
client/src/models/quest.model.ts
client/src/pages/Main.tsx
client/src/pages/Test.tsx
client/src/utils/axios.ts

<strong>
Closes #85
</strong>
```ts
//axios.ts
import axios, { AxiosRequestConfig } from 'axios';
import { getToken } from './tokenUtils';
export const createClient = (config?: AxiosRequestConfig) => {
const axiosInstance = axios.create({
baseURL:
process.env.NODE_ENV === 'development'
? process.env.REACT_APP_MOCK_API_URL
: process.env.REACT_APP_SERVER_API_URL,
headers: {
'Content-Type': 'application/json',
},
withCredentials: true,
timeout: 5000,
...config,
});
...
axiosInstance.interceptors.response.use(
(response) => {
return response;
},
(error) => {
if (error.response.status === 401) {
window.location.href = '/login';
return;
}
if (process.env.NODE_ENV === 'production') {
console.clear();
}
return Promise.reject(error);
}
);
return axiosInstance;
};
export const httpClient = …
```

[FE] 서브퀘스트 생성 구현

---

server/src/apis/quests/dto/create-quest.dto.ts
server/src/apis/quests/dto/create-side-quest.dto.ts
server/src/apis/quests/quests.controller.ts

<strong>
Closes #101 
</strong>
- API 명세 및 코드를 바탕으로 Swagger을 사용하여 퀘스트 API 문서 작성
<br><br>
- NestJS의 Swagger Decorator를 사용하여 문서 작성
- 실사용이 아닌 문서 작성에 필요한 DTO 생성
```ts
// create-quest.dto.ts
...
export class CreateQuestRequestDto extends OmitType(CreateQuestDto, [
'status',
'side',
'createdAt',
'updatedAt',
]) {
@ApiProperty({
type: [OmitType(SideQuestRequestDto, ['questId'])],
example: [
{
content: '사이드 퀘스트 1',
},
{
content: '사이드 퀘스트 2',
},
],
description: '퀘스트 설명 (메인 퀘스트 전용)',
required: false,
})
public side: Omit<SideQuestRequestDto, 'questId'>[];
}
export class UpdateQuestRequestDto extends OmitType(CreateQuestDto, [
'mode',
'side',
'status',
'createdAt',
'updatedAt',
]) {}
export class UpdateSubQuestRequestDto extends PickType(CreateQuestDto, ['title', 'hidden']) {}
export class …
```

[BE] 퀘스트 API Swagger 문서 추가

---

server/src/apis/ranking/dto/ranking-response.dto.ts
server/src/apis/ranking/ranking.module.ts
server/src/apis/ranking/ranking.service.ts
server/src/apis/users/dto/user-profile.dto.ts
server/src/apis/users/users.module.ts
server/src/apis/users/users.service.ts
server/src/app.module.ts
server/src/common/level-calculator/level-calculator.module.ts
server/src/common/level-calculator/level-calculator.service.ts
server/src/common/level-calculator/level-info.interface.ts

<strong>
Closes #104 
</strong>
- 나의 정보 조회 및 특정 사용자의 정보 조회 시 응답 데이터에 레벨 추가
- 랭킹 조회 시 응답 데이터에 레벨 추가
- 1레벨에 필요한 경험치와 최대 레벨 그리고 증가 비율을 넣어 레벨에 필요한 정보를 계산해주는 클래스 생성
- 증가 비율은 0.1로 설정
- 1레벨 maxPoint: 10 2레벨 maxPoint: 1레벨 maxPoint + 10 * 0.1, 3레벨 maxPoint: 2레벨 maxPoint + 10 * 0.1 * 0.1
- point가 0보다 작다면, 1레벨로 보이도록 설정
- point가 최대 레벨에서 요구되는 포인트보다 많다면, 최대 레벨로 보이도록 설정
```ts
import { LevelInfo } from './level-info.interface';
export class LevelCalculatorService {
private levelInfoList: LevelInfo[] = [];
constructor(maxLevel: number = 70, initialExp: number = 10, increaseRate: number = 0.1) {
this.initializedLevelList(maxLevel, initialExp, increaseRate);
}
private initializedLevelList(maxLevel: number, initialExp: number, increaseRate: number) {
let minPoint = 0;
let maxPoint = initialExp;
for (let …
```

[BE] 정보 조회 및 랭킹 조회 시 응답 데이터에 레벨 추가 완료

---

server/src/apis/point/dto/update-point.dto.ts
server/src/apis/point/point.controller.ts
server/src/apis/point/point.module.ts
server/src/apis/point/point.service.ts
server/src/apis/quests/enums/quest.enum.ts
server/src/apis/quests/quests.service.ts
server/src/app.module.ts

<strong>
Closes #
</strong>
- request 값으로 전달받은 상태에 따라 포인트 추가 및 감소 기능 구현 
```ts
const userInfo = await this.userInfoRepository.findOne({ where: { userId } });
if (!userInfo) {
throw new HttpException('fail - User not found', HttpStatus.NOT_FOUND);
}
const quest = await this.questRepository.findOne({
where: { id: questId, userId },
relations: ['sideQuests'],
});
if (!quest) {
throw new HttpException('fail - Quest not found', HttpStatus.NOT_FOUND);
}
```
```ts
private getPointByDifficulty(difficulty: Difficulty): number {
switch (difficulty) {
case Difficulty.Default:
return 2;
case Difficulty.Easy:
return 3;
case Difficulty.Normal:
return 4;
case Difficulty.Hard:
return 5;
default:
throw new HttpException('Invalid difficulty', HttpStatus.UNPROCESSABLE_ENTITY);
}
}
```
- 메인 퀘스트라면, 메인 퀘스트의 …

[BE] 포인트 추가 및 감소 기능 구현 완료

---

server/src/apis/quests/quests.service.ts

<strong>
Closes #149 
</strong>
- 퀘스트 상태 변경 시도 시 변경되지 않는 버그 수정
<br><br>
- 이전 PR에서의 수정으로 인해 빈 값이 발생해 DB에 값이 반영되지 않는 현상 수정(직접 전개 -> 전개 연산자(`...updateQuestDto`))
- 일부 코드 리팩토링
<br><br>
- FE 파트에서 수정 요청 사항 발생 시 수정
<br><br>
- (없음)
<br><br>

[BE] 퀘스트 상태 변경 시도 시 변경되지 않는 버그 수정

---

client/src/api/quests.api.ts
client/src/components/MainBox.tsx
client/src/pages/EditMainQuest.tsx

Closes #152 
```ts
// quest.api.ts
export const getFindOneMainQuest = async (id: number) => {
const response = await httpClient.get<Quest>(API_END_POINT.MAIN_QUEST + `/${id}`);
return response.data;
}
```
<br><br>
```tsx
// EditMainQuests.tsx
const EditMainQuestQuest = () => {
// MainBox에서 Content 값
const { state } = useLocation();
const {
data,
isLoading,
error,
} = useQuery({
queryKey: [BASE_KEY.QUEST],
queryFn: () => getFindOneMainQuest(state.content.id),
});
const [startDate, setStartDate] = useState(data?.startDate);
const [endDate, setEndDate] = useState(data?.endDate);
const [title, setTitle] = useState(data?.title);
const [isDifficulty, setIsDifficulty] = useState(data?.difficulty);
const [sideQuests, setSideQuests] = useState(data?.sideQuests);
const [isPrivate, setIsPrivate] = …
```

[FE] 메인페이지에서 메인퀘스트 수정페이지로 넘어갈 때 바뀐 데이터가 반영되지않는 오류 해결

---

README.md

- 소스 트리 작성 완료
- 전체 아키텍처 이미지 추가
<br><br>
<br><br>
<br><br>
<br><br>

Readme 파일 수정

---

client/src/utils/axios.ts

<strong>
Closes #
</strong>
- 무한 리프레시 토큰 요청 오류를 수정했습니다.
해당 오류는 401 오류 발생시 별다른 분기처리 없이 refresh token 요청을 보내도록 구현되어있어 발생한 오류로 `토큰이 발급된 상태에서 만료된 토큰인지, 토큰이 발급되어있지않아서 발생한 Authrization 오류인지` 확인 후 분기 처리하도록 코드를 수정했습니다.
토큰이 발급되어있으면 로그인 된 상태이면서 토큰이 만료된 상태이므로 refresh token 요청을 보내고 토큰이 없는 상태면 로그인조차 하지 않았기때문에 loginProvider에 의해 로그인 화면으로 가게 됩니다.
```ts
...
axiosInstance.interceptors.response.use(
(response) => {
return response;
},
async (error) => {
const originRequest = error.config;
const hasToken = getToken();
if (error.response.status === 401) {
if (hasToken) {
const refreshedToken = await refreshToken();
setToken(refreshedToken);
return axiosInstance.request(originRequest);
}
}
if (process.env.NODE_ENV === 'production') {
console.clear();
}
return Promise.reject(error);
}
);
...
```

[FE] 토큰 값 유무로 refresh token 요청 분기처리

---

client/src/api/ranking.api.ts
client/src/components/MainBox.tsx
client/src/components/RankingCardList.tsx
client/src/hooks/useRank.ts
client/src/models/ranking.model.ts
client/src/pages/Main.tsx
client/src/pages/Ranking.tsx

Closes #165 
```ts
// ranking.model.ts
export interface RankingItem {
id: number;
nickname: string;
point: number;
rank: number;
level: number;
}
export interface Pagination {
totalPage: number;
nextPage: number;
}
export interface RankingResponse {
ranking: RankingItem[];
pagination: Pagination;
}
```
```ts
// ranking.api.ts
import { API_END_POINT } from '@/constant/api';
import { Pagination, RankingItem } from '@/models/ranking.model';
import { httpClient } from '@/utils/axios';
interface GetRankingParams { 
totalPage: number;
}
export interface RankingResponse {
ranking: any;
data: RankingItem[];
pagination: Pagination;
}
export const getRanking = async ({ totalPage }: GetRankingParams): Promise<RankingResponse> => {
try {
const response = await …
```

[FE] 랭킹 무한스크롤 기능 구현 및 수정페이지 오류해결
